// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "ReplicateTimeseries_types.h"
#include <RcppArmadillo.h>
#include <sitmo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sim_pop_ar
arma::vec sim_pop_ar(const arma::vec& X, const double& N0, const double& b0, const double& b1, const double& rho, const double& sigma, const uint& seed);
RcppExport SEXP _ReplicateTimeseries_sim_pop_ar(SEXP XSEXP, SEXP N0SEXP, SEXP b0SEXP, SEXP b1SEXP, SEXP rhoSEXP, SEXP sigmaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< const double& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const double& >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const uint& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pop_ar(X, N0, b0, b1, rho, sigma, seed));
    return rcpp_result_gen;
END_RCPP
}
// sim_pops_ar
arma::cube sim_pops_ar(const arma::mat& X, const arma::mat& N0_mat, const arma::mat& b0_mat, const arma::mat& b1_mat, const arma::mat& rho_mat, const arma::cube& vcv_cube, const arma::vec& obs_sigma, const uint& n_cores);
RcppExport SEXP _ReplicateTimeseries_sim_pops_ar(SEXP XSEXP, SEXP N0_matSEXP, SEXP b0_matSEXP, SEXP b1_matSEXP, SEXP rho_matSEXP, SEXP vcv_cubeSEXP, SEXP obs_sigmaSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type N0_mat(N0_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type b0_mat(b0_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type b1_mat(b1_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rho_mat(rho_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type vcv_cube(vcv_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type obs_sigma(obs_sigmaSEXP);
    Rcpp::traits::input_parameter< const uint& >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pops_ar(X, N0_mat, b0_mat, b1_mat, rho_mat, vcv_cube, obs_sigma, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// melt_cube
DataFrame melt_cube(arma::cube C);
RcppExport SEXP _ReplicateTimeseries_melt_cube(SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(melt_cube(C));
    return rcpp_result_gen;
END_RCPP
}
// sim_pops
arma::mat sim_pops(const uint& n_gen, const arma::rowvec& N0, const arma::rowvec& r, const arma::mat& alpha, const double& sigma, const uint& seed);
RcppExport SEXP _ReplicateTimeseries_sim_pops(SEXP n_genSEXP, SEXP N0SEXP, SEXP rSEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint& >::type n_gen(n_genSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const uint& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_pops(n_gen, N0, r, alpha, sigma, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ReplicateTimeseries_sim_pop_ar", (DL_FUNC) &_ReplicateTimeseries_sim_pop_ar, 7},
    {"_ReplicateTimeseries_sim_pops_ar", (DL_FUNC) &_ReplicateTimeseries_sim_pops_ar, 8},
    {"_ReplicateTimeseries_melt_cube", (DL_FUNC) &_ReplicateTimeseries_melt_cube, 1},
    {"_ReplicateTimeseries_sim_pops", (DL_FUNC) &_ReplicateTimeseries_sim_pops, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ReplicateTimeseries(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
