# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_pop_ar <- function(X, N0, b0, b1, rho, sigma, seed) {
    .Call(`_repts_sim_pop_ar`, X, N0, b0, b1, rho, sigma, seed)
}

sim_pops_ar <- function(X, N0_mat, b0_mat, b1_mat, rho_mat, vcv_cube, obs_sigma, n_cores = 1L) {
    .Call(`_repts_sim_pops_ar`, X, N0_mat, b0_mat, b1_mat, rho_mat, vcv_cube, obs_sigma, n_cores)
}

melt_cube <- function(C) {
    .Call(`_repts_melt_cube`, C)
}

#' Generate data for simulations.
#' 
#' Generate multi-location, multi-species time series data.
#' 
#' 
#' @param n_time Number of time steps.
#' @param n_loc Number of locations.
#' @param n_spp Number of species.
#' @param mean_b0 Mean for the b0 parameter relating X to N.
#' @param mean_b1 Mean for the b1 parameter relating X to N.
#' @param mean_rho Mean for the rho parameter relating X to N.
#'     This parameter is on the inverse logit scale.
#' @param sigma_b0 Standard deviation for the b0 parameter relating X to N.
#' @param sigma_b1 Standard deviation for the b1 parameter relating X to N.
#' @param sigma_rho Standard deviation for the rho parameter relating X to N.
#'     This parameter is on the inverse logit scale.
#' @param sigma_eps Standard deviation for the epsilon parameter.
#' @param sigma_obs Standard deviation for observation error. Defaults to 0.
#' @param corr_method Method for determining correlations between species.
#'     Options are "none", "phylo", or "random". Defaults to "none".
#' 
generate_data <- function(n_time, n_loc, n_spp, mean_b0, mean_b1, mean_rho, sigma_b0, sigma_b1, sigma_rho, sigma_eps, sigma_obs = 0, corr_method = "none") {
    .Call(`_repts_generate_data`, n_time, n_loc, n_spp, mean_b0, mean_b1, mean_rho, sigma_b0, sigma_b1, sigma_rho, sigma_eps, sigma_obs, corr_method)
}

sim_pops <- function(n_gen, N0, r, alpha, sigma, seed) {
    .Call(`_repts_sim_pops`, n_gen, N0, r, alpha, sigma, seed)
}

